// Banned / unconfirmed claims (EN, FR, AR). Shared by check:content and the dictionary audit.
// Allowed documents wording: "Ingredient lists and safety data sheets on request".
export const RULES = [
  // English
  ["certified / certification", /\bcertif(ied|ication|ications|icates?)\b/i],
  ["Ecocert", /\becocert\b/i],
  ["USDA / FDA", /\b(usda|fda)\b/i],
  ["ISO / GMP", /\b(iso|gmp)\b/i],
  ["organic", /\borganic\b/i],
  ["COA", /\bCOAs?\b/],
  ["quality tested", /quality[- ]tested|tested for quality/i],
  ["ethically produced", /ethical(ly)? (produced|sourced|made)|ethically/i],
  ["leading", /\bleading\b/i],
  ["cruelty-free", /cruelty[- ]free/i],
  ["vegan", /\bvegan\b/i],
  ["anti-aging", /anti[- ]?(aging|ageing|age)\b/i],
  ["skin repair", /skin[- ]repair/i],
  ["detox", /\bdetox/i],
  ["client/partner counts", /\b\d[\d,.]*\+?\s+(happy\s+)?(clients|customers|partners|brands|retailers|businesses)\b/i],
  ["minimum order wording", /\b(total|per product|per item)\b[^.\n]{0,20}\b(minimum|MOQ)\b|\b(minimum|MOQ)\b[^.\n]{0,25}\b(in total|per product|per item|total)\b|\b50 pieces (per product|total|per item)\b/i],
  // French
  ["FR certifié", /\bcertifi(é|e|ée|és|ées|cation|cations|cat|cats)\b/i],
  ["FR bio", /\b(bio|biologiques?)\b/i],
  ["FR COA", /\bCOA\b/],
  ["FR ISO/BPF", /\b(iso|bpf|gmp)\b/i],
  ["FR qualité testée", /qualit(é|e) test(é|e)e?|test(é|e)e? qualit/i],
  ["FR éthique", /(production|fabriqu(é|e)|produit)s?\s+(é|e)thique|(é|e)thiquement/i],
  ["FR leader", /\bleaders?\b|num(é|e)ro (un|1)/i],
  ["FR sans cruauté", /sans cruaut(é|e)/i],
  ["FR végan", /\bv(é|e)gan\b|v(é|e)g(é|e)talien/i],
  ["FR anti-âge", /anti[- ]?(â|a)ge/i],
  ["FR réparation peau", /r(é|e)paration de la peau|r(é|e)pare la peau/i],
  ["FR détox", /\bd(é|e)tox/i],
  ["FR comptes clients", /\b\d[\d\s.]*\+?\s+(clients|partenaires|marques|revendeurs)\b/i],
  // Arabic
  ["AR معتمد", /معتمد|معتمدة|مصدّق|مصدق|شهادة|شهادات|حاصل على/],
  ["AR إيكوسير", /إيكوسير|ايكوسير|اكوسيرت/],
  ["AR عضوي", /عضوي|عضوية/],
  ["AR COA/ISO", /COA|SDS|ISO|GMP/],
  ["AR جودة مختبرة", /اختبار الجودة|مختبر(ة)? الجودة|تم اختبار|مختبرة/],
  ["AR أخلاقي", /أخلاق/],
  ["AR رائد", /\bرائد|الرائد/],
  ["AR بدون قسوة", /خال(ٍ|ي)? من القسوة|بدون قسوة|القسوة|غير مختبر على الحيوان/],
  ["AR نباتي", /نباتي|فيجان/],
  ["AR مضاد للشيخوخة", /الشيخوخة|مضاد(ة)? للتجاعيد/],
  ["AR إصلاح البشرة", /إصلاح البشرة|ترميم البشرة/],
  ["AR ديتوكس", /ديتوكس|السموم/],
  ["AR أعداد العملاء", /\d[\d,.]*\+?\s+(عميل|عملاء|شريك|شركاء|علامة)/],
];
